[package]
name = "haider-tui"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
haider-protocol = { path = "../haider-protocol" }
haider-rpc = { path = "../haider-rpc" }
haider-client = { path = "../haider-client" }
zeroize.workspace = true
base64.workspace = true
ratatui.workspace = true
serde.workspace = true
termbg.workspace = true
tokio.workspace = true
serde_json.workspace = true
unicode-segmentation.workspace = true
unicode-width.workspace = true
ratatui-image = { version = "11", default-features = false, features = ["crossterm"] }
image = { version = "0.25", default-features = false, features = ["png"] }

[dev-dependencies]
zeroize.workspace = true
tempfile.workspace = true
tokio = { workspace = true, features = ["test-util"] }

[lints]
workspace = true
