[package]
name = "haider-tui"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
haider-protocol = { path = "../haider-protocol" }
base64.workspace = true
ratatui.workspace = true
termbg.workspace = true
tokio.workspace = true
serde_json.workspace = true
unicode-width.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }

[lints]
workspace = true
