[package]
name = "haider-store"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
blake3.workspace = true
crc32fast.workspace = true
getrandom.workspace = true
haider-platform = { path = "../haider-platform" }
haider-protocol = { path = "../haider-protocol" }
hex.workspace = true
image.workspace = true
rusqlite = { workspace = true, features = ["blob", "hooks"] }
rmp-serde.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
base64.workspace = true
tempfile.workspace = true

[lints]
workspace = true
