[package]
name = "haider-daemon"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
base64.workspace = true
blake3.workspace = true
getrandom.workspace = true
haider-client = { path = "../haider-client" }
haider-core = { path = "../haider-core" }
haider-accounts = { path = "../haider-accounts" }
haider-protocol = { path = "../haider-protocol" }
haider-provider = { path = "../haider-provider" }
haider-rpc = { path = "../haider-rpc" }
haider-tools = { path = "../haider-tools" }
rustix.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
haider-store = { path = "../haider-store" }
tempfile.workspace = true

[lints]
workspace = true
