[package]
name = "haider-stt"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
futures-util.workspace = true
haider-platform = { path = "../haider-platform" }
hex.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tempfile.workspace = true
tokio.workspace = true
tokio-tungstenite.workspace = true
url.workspace = true
zeroize.workspace = true
zip.workspace = true

[target.'cfg(not(target_os = "android"))'.dependencies]
cpal.workspace = true

[dev-dependencies]

[lints]
workspace = true
